version: '3.9'

services:

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './src'
      - '/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start